---
title: "How to ask Amex for a retention offer?"
categories: [personal finance, amex]
author: "Salman Faris"
date: "04 10 2024"
jupyter: python3
format:
  html:
    toc: true
    html-math-method: katex
execute: 
  enabled: false
  cache: false
# bibliography: references.bib
draft: false
---

I've scoured the internet (read: reddit) for this one. I found a lot of people sharing what was offered to them as their retention offer but close to none of people sharing what they actually said or how they actually contacted Amex to get it. 

Some people would just say, oh I go on the chat and then just ask for the retention offer. That's actually quite helpful considering most people would guess that retentions are most probably done via phone – broadband and telco retention comes to mind. But what do you say to ask them for a retention offer? Do you fluff them up first? Do you go straight into asking with a straight expression? What do you do?

I speak English as a second language. If you've learnt another language in your life beyond your mother tongue, you would know that knowing what and how to speak is deeply contextual. I've scored English essays, passed English vivas, but when I was trying to get my first haircut in the UK, I have no idea how to describe what I wanted. I showed a picture, but the barber wanted a precise description like "how many inches do you want to take off the fringe?" for which I replied with "What is a fringe...?". So I'm gonna tell you what I ended up doing to ask Amex for a retention offer.

Obviously, I winged it. I went on to chat, and literally just went through the no BS route. Feel free to copy this. I said:

> Me: Hi Amex, is there any retention offer for me? The fee seems quite high and I'm considering closing it. It just doesn't make sense to keep it at the moment...

That's it. No fluff, no introductions, just went straight begging for a retention offer. They'll come back saying their fees is justified with the benefits. If you've run the math, you'll see that the Gold card (pretty sure ditto for the Plat) indeed yields a benefit that is at least worth £285 on "tangible" benefits when the card itself costs £195 annually (as of 2024). You get £120 worth of Deliveroo annually (assuming you do at least 4x take-outs and groceries each month) and roughly £69 + £24 x 4 = £165 worth of airport lounges. And this is just on "tangible" benefits  where I haven't factored in free travel insurance, 2x points on airline spend, discount on car hires and so on. 

So even minus the extra Amex offers, and assuming you're not inflating your lifestyle for the sake of matching the card benefits, you break even pretty easily with this card. Despite this, however, you should come back at them saying:

> Me: No, I get that the fees are justified, I'm just not happy that the benefits are netted out by the fees. Is there a retention offer for me to stay with the card?

After you said this, they should give in and come out with a retention offer. This offer, unfortunately, is take it or leave it. I've tried negotiating but the rep said no. It does make sense since I'm pretty sure the retention offers are done by a single-output ML algorithm and so it's really beyond the rep's control. Now it's up to you to decide to take it or leave it and cancel the card.

That's it. That's how you ask for a retention offer from Amex.