---
title: "A mathematical take on when to take a loan such as ASB Financing"
description: "We look at formalizing the parity between investing with a disposable capital versus with a financed leveraged capital in ASB."
categories: [quant, investment, strategies]
author: "Salman Faris"
date: "22 04 2024"
jupyter: python3
format:
  html:
    toc: true
    html-math-method: katex
execute: 
  enabled: false
  cache: false
---

*Disclaimer: Nothing written here is investment advice.*

# What is ASB financing

ASB financing is a financing tool to maximize investment in Malaysia's ASB (Amanah Saham Berhad) unit trust fund. It is an excellent product for Bumis (controversial... I know). Essentially, it allows for leverage with only interest as a risk; which is great not just for consumers but with such few parameters, it makes modelling easy as well. Unfortunately, albeit expected, there's not much arbitrage in this space – maybe only reverse arbitrage where financial institutions can screw consumers over.

But risk is risk and I want to minimize loss and regrets to the lowest low. Like all investments, betting strats and literally anything that involves counting numbers, I like to think of parities – for example, how does a $1 injection in a risk-free investment compares to one with risk? If there is zero difference, then it is obvious to go with the risk-free asset. We will be reasoning in this exact same line.

# Decision parity

I am going to put some numbers down so that the parity justification makes more sense. If I have some disposable RM20,000 to invest, an investment in ASB without financing with a dividend rate of 5% would yield me RM1000. However, with financing at a 4% interest rate, the same RM20,000 would yield me only RM200. Ouch, not great. So how do we achieve parity assuming interest and dividend rates are fixed? Well, you would have to take financing with a starting capital of RM100,000. So I would have to take a loan that is 5x the value of my disposable starter. Is this worth it? 

Note that you take financing over a set amount of years so the interest rate can change with years. But the dividend rate is the same regardless if you take financing or not so we can essentially treat it as constant. Let's look at what happens if we perturb the interest rate a bit assuming the dividend rate holds at 5%. Again take a starting capital of RM100,000. With each 1% interest rate decrement, we see that the yield increases from RM1000 to RM2000 and then to RM3000 and eventually to RM5000 where the interest rate is zero. So if the interest rate behaves stochastically (as it should), we should see some good years where the returns can get lucrative. Just think about the amount of disposable capital you need to have to attain these returns – it scales 2x with each 1% interest rate decrement. So to attain a RM3000 return, you need RM60,000 to start with which can be quite a jump.

*Just a short disclaimer that there can be terrible years as well if the dividend rate falls below the interest rate. As of 2024, we are seeing ASB stabilizing a bit despite the terrible Malaysian market conditions and [insane amount of foreign funds outflow](https://www.isaham.my/foreign-funds). So we shouldn't be seeing a crossover between the two rates anytime soon unless BNM starts to do something funny possibly due to global economy forcing Malaysia to be reactive.*

So how do we formalize the parity argument in this context? Can we give answer to questions like "how much starting capital should I need before the risk due to premiums becomes unprofitable so that I can focus on investment without financing"? I aim to answer questions like these in the future where we look into annual movements and observe with a closer lens the dynamics of interest, dividend and reinvested capital – this sounds like a three-body problem and the maths can get musty real quick. This post, however, is a primer to set up a tool so we can reason about what I just said in a logical way.

# Mathematical primer
An investment capital $C$ yields a return of $f(C; d) = f(C) = dC$ with dividend rate $d$. With financing, the returns get discounted with an interest rate $r$ so an initial capital $C$ yields a return of $\tilde{f}(C; d, r) = \tilde{f}(C) = (d-r)C = f(C) - rC$. Observe that these are linear functions in $C$ (and even in $d$ and $r$). Rather than constraining our model to the space of linear functions, let's make this model more flexible (in hopes that it becomes more useful) by relaxing this assumption. For example, consider another financing option that gives returns that grows quadratically in $C$. This is very much a plausible returns use case – whether such an opportunity exists or not in the real world is another story (please let me know if you find any investment opportunity that grows quadratically in capital!). If we were to assume returns are linear in $C$, then the model would not have been applicable for this financing option. 

So what's a good model for returns? Just thinking of returns that scale with capital and nothing else, we expect returns to be monotone in $C$. That is, with growing $C$, the returns should grow as well. To make life easier, we will actually assume strict monotonicity on our return (functions) and we shall see why in a bit. Note that we are **not** talking about annual growth on returns given an initial capital which can have deviations in dividend and interest rates. In this case, we expect randomness to kick in and monotone is not a sensible assumption. However, this is something we will hopefully look at in the future.

With this in place, we can now reason about parity. Let $C_1 > 0$ be your disposable capital; $C_1$ should be the capital that maximizes non-financed returns as you can always invest any capital $C \leqslant C_1$ without financing. Then parity in ASB financing is attain at a capital $C_2 \geqslant C_1$ where the returns with financing is at least equivalent to returns in the interest-free investment. Define *returns without financing* to be a strictly monotone function $f: [C_0, C_1] \to \mathbb{R}$ where $C_0 \geqslant 0$, and let $\tilde{f}: [C_1, \infty) \to \mathbb{R}$ be the *returns with financing* which we also assume strict monotonicity. Then $C_2$ is simply the capital that satisfies $\tilde{f}(C_2) = f(C_1)$. And because of strict monotonocity, we can actually compute $C_2$ by simply inverting $\tilde{f}$ to get $C_2 = \tilde{f}^{-1}(f(C_1))$. Where $\tilde{f}$ is a linear function, this is pretty straightforward to do.

Using returns in the linear setting, we have 
$$
C_2 = \frac{f(C_1)}{d-r} = \frac{dC_1}{d-r}.
$$

And we can compute the parity difference $\Pi(C_1, C_2) := |C_2 - C_1|$ where in the linear setting reduces to:

$$
\Pi(C_1, C_2) = |C_2 - C_1| = C_1 \left| \frac{r}{d-r} \right|.
$$

Using parity difference, we can see just how dramatic the disposable capital and interest rate can affect the parity capital $C_2$ in the linear setting. With a dividend rate of 5% and interest rate of 4%, the parity difference gives $\Pi(C_1, C_2) = 4C_1$, whereas just lowering the interest rate by 1% to 3%, the parity difference gives $\Pi(C_1, C_2) = 1.5C_1$. With a disposable capital of $C_1 =$ 20,000, the parity difference at 4% is 80,000 whereas at 3% is 30,000 which is a stark difference. That is, parity point is achieved at $C_2 =$ 100,000 and 50,000 respectively, essentially halved! Similarly, if you were to fix the interest rate at 4%, a disposable capital of 20,000 would give a parity difference of 80,000 whereas a disposable capital of 100,000 would give a parity difference of 400,000. Massive difference! This is why it is important to have mathematical tools like this to enable better investment decisions.

## Measuring poor financing choices with curves

Recall that returns is a function of capital, but also assumes a fixed dividend and interest rate $r$. By relaxing the interest rate $r$ assumption in $\tilde{f}(C; d, r)$, we see that $r$ defines the family of *financed* curves $\tilde{f}(C, r; d)$. If we further relax the fixed dividend rate $d$ assumption, we obtain a wider family of curves for both $f(C, d, r)$ and $\tilde{f}(C, d, r)$. So how can we measure which *financed* curves are worse? One metric that I think is useful is the area enclosed between $f$ and $\tilde{f}$, bounded by the minimum and maximum of $f$. Where $f$, $\tilde{f}$ are linear functions in $C$, this area looks like a rhombus and the goal is to make this rhombus as small as possible. Let $C_0$ be the minimum amount of invested capital where $0 \leqslant C_0 \leqslant C_1$; this should be the value that minimizes $f$. Then using very basic geometry, you can obtain this metric as the following quantity:

$$
\begin{align*}
\mathrm{Loss}(f, \tilde{f}) &= \int_{[C_0, C_1]} \left(f(C) - \min_{C} f(C)\right) \mathrm{d}C + \int_{[C_1, C_2]} \left(\max_{C} f(C) - \tilde{f}(C)\right) \mathrm{d}C \\
&= \int_{[C_0, C_1]} \left(f(C) - f(C_0)\right) \mathrm{d}C + \int_{[C_1, C_2]} \left(f(C_1) - \tilde{f}(C)\right) \mathrm{d}C.
\end{align*}
$$

So a good financing option – where interest rate is minimized – should be where the loss metric above is minimized. It can be rather tedious to compute this, especially when the return models $f$ and $\tilde{f}$ gets bloated with other discount rates to make the model more accurate. Thankfully, however, there is an equivalence between this metric and the parity difference under certain conditions suggesting that it can be sufficient to look at the parity difference.

If one examines the loss function above, one observe that the first part is entirely defined by $f$. This quantity acts only as a bias term in the loss computation. Rather, the second quantity is what we should put our focus on. In the second integral, note that $f(C_1)$ is fixed when $f$ is fixed. But both $f$ and $\tilde{f}$ is dependent on the dividend rate $d$. So suppose we fix a dividend rate, we can then minimize the loss on $\tilde{f}$ just over the space of possible interest rates and functional forms. Let's make this even simpler and just focus on linear forms. In this case, it's just a matter of minimizing interest rates which is equivalent to minimizing the range $[C_1, C_2]$. And that was exactly the parity difference we defined before!

# So what have we learnt?

In this post, we looked at formalizing parity differences in investing in ASB with and without financing. From there, we build a metric to measure poor financing choices using a geometrical approach. This formalism gives us a tool to logically reason, for example, on finding a comfortable threshold for taking a loan to invest.

What next? From here, we can use this formalism to measure  annual compound returns either via a deterministic or stochastic approach. Running simulations should also be straightforward using this framework.

With this formalism, the best answer I can give for now (to myself, this is not investment advice!) on what set level to start taking financing is the following: given a disposable investment amount $C_1$, take financing for ASB if the initial financing amount satisfies $C_2 = \tilde{f}^{-1}(f(C_1))$ such that $\log C_2/C_1 \approx 1$. I'm excited to see how this opinion will change when we factor in annual dynamics.