---
title: "resources"
about:
  template: solana
  image-width: 10em
---

### Undergraduate stuff @ KCL

- My [dissertation](/downloads/dissertation.pdf){target="_blank"} – Diophantine Equations, supervised by Prof. Payman Kassaei.

I wrote my undergrad math notes in $\LaTeX$ to help me understand better. These notes can replace lecture notes and are around 100 pages long each. They can be accessed via this [repository](https://github.com/salfaris/kcl-notes). Notable ones include:

- [6CCM350A Rings and Modules](https://github.com/salfaris/kcl-notes/raw/main/level-6/rings-modules.pdf){target="_blank"} – based on lectures by Prof. Nicholas Shepherd-Barron, Fall 2020.
- [6CCM359A Numerical and Computational Methods](https://github.com/salfaris/kcl-notes/raw/main/level-6/num-methods.pdf){target="_blank"} – based on lectures by Prof. Benjamin Doyon, Fall 2020.
- [5CCM224A Introduction to Number Theory](https://github.com/salfaris/kcl-notes/raw/main/level-5/num-theory.pdf){target="_blank"} – based on lectures by Dr. James Newton, Fall 2019.
- [5CCM226A Metric Spaces and Topology](https://github.com/salfaris/kcl-notes/raw/main/level-5/MST.pdf){target="_blank"} – based on lectures by Dr. Jerry Buckley, Fall 2019.

### Postgraduate stuff @ Oxford

- My [dissertation](https://www.cs.ox.ac.uk/michael.benedikt/thesesadvancedmsc.html){target="_blank"} –  “Enhancing VAE-learning on spatial priors using graph convolutional networks”, supervised by Seth Flaxman, Swapnil Mishra and Elizaveta Semenova.
- Implemented "Variational Graph Auto-Encoders" (Kipf and Welling, 2016) in JAX as part of my dissertation. Source code can be found in [this repo](https://github.com/salfaris/vgae-jax).
- Reproduced and extended "Inference Suboptimality in Variational Autoencoders" (Cremer et. al, 2018) using JAX. Built together with Basim Khajwal, Snehal Raj and Vasileios Ntogram. Source code can be found in [this repo](https://github.com/ATML-2022-Group6/inference-suboptimality).